[build]
  command = "CI='' npm run build"
  publish = "dist"
  environment = { 
    VITE_SUPABASE_URL = "https://gstqkdcxbtuivtflpsop.supabase.co",
    VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdzdHFrZGN4YnR1aXZ0Zmxwc29wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA3NTIwOTgsImV4cCI6MjA3NjMyODA5OH0.moFSj41EkPym1GavcKHEwl1KVbbfOKHtV06kgGRm1_I"
  }
